### ISSUE TITLE
Support Array type v-model

### ISSUE THREAD

**Issue by foundryspatial-duncan** [dai-siki/vue-switch#2]
If you do something like
``` vue
<div v-for="thing in things">
  {{ thing }} <vue-switch :value="thing" v-model="enabled"></vue-switch>
</div>
```
Then `enabled` will be an array like this:
``` javascript
data() {
  return {
    things: [
      'thing1',
      'thing2',
      'thing3',
    ],
    enabled: [
      'thing2',
    ],
  };
},
```
It would be nice to support this type of `v-model` so `vue-switch` can work just like a checkbox.

**Comment by dai-siki** [comment]
I understand what you mean, but that is another component, the use of this component is a function of the opening and closing, it is recommended that you copy part of this component to make a new suit for your components
